# Generated by Django 5.2.7 on 2025-10-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('duenno', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
