# Generated by Django 5.2.7 on 2025-10-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mascota_delete_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_incorporacion',
            field=models.DateTimeField(null=True),
        ),
    ]
