# Generated by Django 5.2.7 on 2025-10-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_doctor_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.CharField(max_length=100),
        ),
    ]
