# Generated by Django 5.2.7 on 2025-11-02 22:21

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_cita_doctor_alter_cita_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_incorporacion',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
    ]
