# Generated by Django 5.2.7 on 2025-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_mascota_fecha_incorporacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_incorporacion',
            field=models.DateTimeField(null=True),
        ),
    ]
